language: php
sudo: required
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

before_script:
  - composer update --prefer-source $LOWEST_DEPS

script:
  - ./bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

cache: vendor
